### PR TITLE
Deleted images

### PR DESCRIPTION
**Pull request by sriksrik7**
Deleted the images

### CODE REVIEW

**Review by akrish3 — APPROVED** [review]
Agreed on Deletion of the architecture  image

**Comment by tohearen** [comment]
We want to also delete ui.jpg as a part of this change.

**Review by Emay-Pandarakutty — CHANGES_REQUESTED** [review]
Agreed on architecture.jpg deletion, but story cover more deletions - mages/ui.jpg and Trekker folder still present.

**Comment by sriksrik7** [comment]
Addressed the review comments to delete both ui.jpg and trekker project folder.

**Review by tohearen — APPROVED** [review]
Looks good. Approved.

**Review by Emay-Pandarakutty — APPROVED** [review]
Agreed on deltions

**Pull request merged**
